### ISSUE TITLE
Wikipedia categories - Leaves Identification

### ISSUE THREAD

**Issue by marfox** [dbpedia/dbpedia-links#16]
Investigate YAGO approach

**Comment by sm86** [comment]
An implementation specific doubt, I don't know if this is a right place to put in. 

In the current Implementation, the code gets all the pages from page database table, stores in file, indexing it with lucence and then searches the indexed with namespace=0. Then step 2 is fired through loop. Then we loop through the results of step 2 to obtain step 3. The same way for step 4. 

**Proposed Approach:**
I spoke to @kkasunperera and he mentioned above approach is implemented mainly to avoid issues of heap size. Can we have a nested queries for the same called from a single java function.
```
SELECT * FROM (select * from `category`                              #GET LEAF CATEGORIES
WHERE `cat_subcats`=0 
	AND `cat_pages`>0 
        AND `cat_pages`<90                                 #threshlod value here = 90 
        AND cat_id in ( select cl_from from categorylinks  #Get article Categories
					where cl_to in (SELECT page_title FROM `page` 
									where page_namespace=0)) # Getting the main articles
	) AS leaf 
JOIN page as pageTable 
ON  leaf.cat_title = pageTable.page_title  # Get parents of categorylinks
WHERE pageTable.page_namespace=14;
```
Anyways we store the output of this query into Node table and Edge table after the query.  We can use a file writer after this step, if needed. I can also look around for creating MySQL VIEW for same instead?
Is there anything I have missed, can we have this approach implemented? @marfox @jimkont 
Waiting for a feedback. Thank you. 
P.S: I have to make few modifications in SQL query, and also missed file type checking. It is for illustrative purpose only,  I will do that once this approach approved .
